language: perl

#install:
#  - cpanm -n Foo::Bar

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"

#before_script: /bin/true

script: HARNESS_IS_VERBOSE=1 prove -lv t xt

#after_script: /bin/true
